### ISSUE TITLE
About Us link

### ISSUE THREAD

**Issue by bradAnders** [OSU-USLI-18/OSU-USLI-18.github.io#10]
Have About Us link to a detailed list of team members, not back to the home page. Home page should have brief list of names, but bios and pictures can go on About Us.

I attached an image of the mission profile, which should go somewhere.
![img_0341](https://user-images.githubusercontent.com/32400955/31755054-d2223eac-b450-11e7-9484-7cdf83f6a80d.PNG)

**Comment by zainkai** [comment]
For reference

![530080285](https://user-images.githubusercontent.com/18077225/31754624-b3ca4f56-b44d-11e7-807e-1abb2ddae9f4.jpg)

**Comment by zainkai** [comment]
**Active** on the sidebar portion. 

Note for me:
https://www.w3schools.com/howto/howto_css_sidenav_buttons.asp

**Comment by zainkai** [comment]
Finished the sidebar. I'll put up an about us page tomorrow.

**Comment by bradAnders** [comment]
How do you access the side bar on mobile?

**Comment by zainkai** [comment]
@bradAnders You can tap the sidebar once on mobile and it will open. I have the AboutUS page filled with team member names and emails, what else do you specifically want on the page?
