### ISSUE TITLE
Sponsorship Page

### ISSUE THREAD

**Issue by charliesanford2017** [OSU-USLI-18/OSU-USLI-18.github.io#18]
Could you guys make a sponsorship page on the website to display company logos for promotional purposes? I can email whoever the images to be used, just let me know..

Thank you.

-Charlie

**Comment by struthj** [comment]
For sure!
Could you upload the images to the "USLI - Website" folder on google drive? We can add this page when finals week is over, shouldn't take too long

**Comment by struthj** [comment]
@charliesanford let me know if you think anything else needs to be added!

**Comment by charliesanford2017** [comment]
@struthj I added a zip file to the "USLI - Website" folder with logos for RobotShop.com. If you could add that today that would be awesome because our discount code is pending upon it. Just use whatever image looks/fits best. The page looks great thank you very much!

**Comment by zainkai** [comment]
@struthj completed this in the following commit: a19f107702e9177769fd6f4f10e08d09841aea54
